# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171215_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账号表', 'verbose_name_plural': '账号表'},
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已报名'), (1, '未报名')], default=1),
        ),
    ]
