# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '分支机构', 'verbose_name_plural': '分支机构'},
        ),
    ]
